apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/karthikasturi/gitops-demo
    targetRevision: HEAD
    path: helm-charts/my-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: environment
          value: "staging"
        - name: replicaCount
          value: "2"
        - name: image.tag
          value: "v1.0.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
