apiVersion: v2
name: my-app
description: A sample web application for ArgoCD demo
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
