apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/argocd-demo
    targetRevision: HEAD
    path: helm-charts/my-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: environment
          value: "dev"
        - name: replicaCount
          value: "1"
        - name: image.tag
          value: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
